name: Node.js CI/CD && Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laundry:latest


      - name: Check SSH key fingerprint (safe)
        run: |
            set -e
            mkdir -p ~/.ssh
            echo "${SSH_PRIVATE_KEY}" > ~/.ssh/key
            chmod 600 ~/.ssh/key
            echo "Public key derived from secret:"
            ssh-keygen -y -f ~/.ssh/key | head -c 80; echo "..."
            echo "Fingerprint:"
            ssh-keygen -lf ~/.ssh/key
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server (ngrok)
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.PUBLIC_IP }}
            port: 19480
            passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                docker pull ${{ secrets.DOCKER_USERNAME }}/laundry:latest
                docker stop laundry || true
                docker rm laundry || true
                docker run -d --name laundry -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/laundry:latest